#!/bin/bash

installRecord="./install-record.txt"

if [ "$EUID" -ne 0 ]; then
	echo "Please run as root"
	exit 1
fi

if [ ! -f "$installRecord" ]; then
	echo "Install record not found, either you deleted 'install-record.txt', or didn't run 'install'"
	exit 1
fi

echo "Removing files on 'install-record.txt'"
read -p "Are you sure? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
	cat "$installRecord" | xargs rm -rfv
	echo "Removing 'install-record.txt'"
	rm -v "$installRecord"
fi
