#!/usr/bin/python3
import os
from update_tool_python.updater import updater_main
from update_tool_python.common.updatemodule import getlink

DIR = getlink(__file__)
if DIR == '/usr/local':
        DATADIR = os.path.join(DIR, 'share', 'update_tool_python', 'data')
else:
        DATADIR = os.path.join(DIR, 'update_tool_python', 'common', 'data')

if __name__ == "__main__":
	updater_main.main(DATADIR, DIR)
